import { Dimensions, StyleSheet } from 'react-native';
import { theme } from '../../theme/appTheme';

const { height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f1f5f9',
    overflow: 'hidden',
  },

  // ── Header ──
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    zIndex: 10,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  headerIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 9,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: theme.colors.white,
    letterSpacing: 0.3,
  },
  headerSubtitle: {
    fontSize: 11,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.75)',
    marginTop: 1,
  },
  headerMenuBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // ── Map ──
  mapArea: {
    position: 'absolute',
    top: 76,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  map: {
    flex: 1,
  },
  userMarkerIcon: {
    width: 50,
    height: 50,
  },
  lineStartDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#0ea5e9',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  lineStartDotActive: {
    backgroundColor: '#ef4444',
  },
  lineEndArrowWrap: {
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lineEndArrowHead: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderBottomWidth: 12,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#0ea5e9',
  },
  lineEndArrowHeadActive: {
    borderBottomColor: '#ef4444',
  },

  // ── Overlays ──
  overlaysContainer: {
    position: 'absolute',
    top: 76 + 14,
    left: 14,
    right: 14,
    zIndex: 5,
  },
  lineNumberCard: {
    backgroundColor: 'rgba(255,255,255,0.97)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  lineNumberLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  lineNumberLabel: {
    fontSize: 14,
    color: '#334155',
    fontWeight: '600',
  },
  lineNumberRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  lineStepBtn: {
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  lineStepBtnHidden: {
    width: 28,
    height: 28,
  },
  lineNumberCount: {
    fontSize: 15,
    color: theme.colors.gradientEnd,
    fontWeight: '800',
  },
  mapActions: {
    position: 'absolute',
    top: 70,
    right: 0,
    gap: 10,
  },
  mapActionBtn: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
  },

  // ── Bottom Sheet ──
  bottomSheet: {
    position: 'absolute',
    bottom: -height * 0.45,
    height: height * 0.75,
    left: 0,
    right: 0,
    backgroundColor: theme.colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    elevation: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -5 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    zIndex: 100,
  },
  sheetHandleWrap: {
    width: '100%',
    alignItems: 'center',
    paddingTop: 14,
    paddingBottom: 10,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#cbd5e1',
    borderRadius: 4,
  },

  // Sheet Header
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  sheetTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  totalPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 20,
  },
  totalPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.gradientEnd,
  },

  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statChipDone: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 20,
  },
  statChipProgress: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#fffbeb',
    borderWidth: 1,
    borderColor: '#fde68a',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 20,
  },
  statChipTotal: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 20,
  },
  statChipText: {
    fontSize: 11,
    fontWeight: '700',
  },
  progressBarBg: {
    height: 3,
    backgroundColor: '#e2e8f0',
    marginHorizontal: 20,
    marginBottom: 12,
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: theme.colors.gradientStart,
    borderRadius: 4,
  },
  listContainer: { flex: 1 },
  housesScroll: {
    paddingHorizontal: 20,
    paddingBottom: 8,
    gap: 12,
    alignItems: 'flex-start',
  },
  housesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 20,
    paddingBottom: 40,
    gap: 10,
    justifyContent: 'flex-start',
  },

  // ── House Card ──
  houseCard: {
    width: 124,
    height: 150,
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
  },
  houseCardDone: {
    borderColor: theme.colors.gradientStart,
  },
  houseCardProgress: {
    borderColor: '#f59e0b',
  },
  houseCardSelected: {
    elevation: 6,
    shadowOpacity: 0.15,
    transform: [{ scale: 1.02 }],
  },
  houseImageArea: {
    flex: 1,
    backgroundColor: '#f8fafc',
    justifyContent: 'center',
    alignItems: 'center',
  },
  housePreviewImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  houseImageAreaDone: {
    backgroundColor: '#ecfdf5',
  },
  houseImageAreaProgress: {
    backgroundColor: '#fffbeb',
  },
  cardBadgeDone: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: theme.colors.gradientStart,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardBadgeProgress: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#f59e0b',
    borderWidth: 1.5,
    borderColor: '#fff',
  },
  houseCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 9,
    paddingVertical: 7,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    gap: 3,
    backgroundColor: '#fff',
  },
  houseCardFooterNumbers: {
    flex: 1,
    gap: 2,
  },
  houseCardFooterDone: {
    backgroundColor: '#f0fdf4',
  },
  houseCardNumber: {
    flex: 1,
    fontSize: 11,
    fontWeight: '700',
    color: '#334155',
    letterSpacing: 0.2,
  },
  houseCardNumberDone: {
    color: theme.colors.gradientEnd,
  },
  houseCardHuf: {
    fontSize: 9,
    fontWeight: '600',
    color: '#64748b',
    letterSpacing: 0.3,
  },
});

export default styles;
